# Generated by Django 3.1 on 2022-03-13 00:26

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=179, unique=True)),
                ('phone_number', models.CharField(max_length=9, validators=[customers.models.phone_validate])),
                ('direction', models.CharField(max_length=170)),
                ('district', models.CharField(choices=[('1', 'Ate'), ('2', 'Barranco'), ('3', 'Breña'), ('4', 'Chorrillos'), ('5', 'Cieneguilla'), ('6', 'Comas'), ('7', 'El Agustino'), ('8', 'Independencia'), ('9', 'Jesus Maria'), ('10', 'La Molina'), ('11', 'La Victoria'), ('12', 'Lince'), ('13', 'Los Olivos'), ('14', 'San Juan de Lurigancho'), ('15', 'Magdalena del Mar'), ('16', 'Miraflores'), ('17', 'Pachacamac'), ('18', 'Lima'), ('19', 'Pueblo Libre'), ('20', 'Rimac'), ('21', 'San Borja'), ('22', 'San Isidro'), ('23', 'San Juan de Miraflores'), ('24', 'San Luis'), ('25', 'San Martín de Porres'), ('26', 'San Miguel'), ('27', 'Santa Anita'), ('28', 'Santiago de Surco'), ('29', 'Surquillo'), ('31', 'Villa El Salvador'), ('32', 'Villa María del Triunfo')], max_length=27)),
                ('reference', models.CharField(max_length=170)),
                ('is_regular_client', models.BooleanField(default=0)),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
