# Generated by Django 3.1 on 2022-03-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0003_auto_20220312_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Peid'), ('2', 'Pending')], default='Pending', max_length=13)),
                ('pay_method', models.CharField(choices=[('C', 'Cash'), ('T', 'Transfer')], max_length=12)),
                ('bank', models.CharField(choices=[('1', 'BCP'), ('2', 'BBVA'), ('3', 'SCOTIABANK'), ('4', 'INTERBANK'), ('5', 'BANCO DE LA NACION'), ('6', 'None')], default='None', max_length=27)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('register_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('register_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='products.product')),
            ],
        ),
    ]
