# Generated by Django 3.1 on 2022-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('1', 'BCP'), ('2', 'BBVA'), ('3', 'SCOTIABANK'), ('4', 'INTERBANK'), ('5', 'BANCO DE LA NACION'), ('6', 'None')], default='6', max_length=27),
        ),
    ]
