# Generated by Django 3.1 on 2022-03-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
