# Generated by Django 3.1 on 2022-04-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220327_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
