# Generated by Django 3.1 on 2022-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=170)),
                ('unity', models.CharField(max_length=170)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('register_date', models.DateTimeField()),
            ],
        ),
    ]
