# Generated by Django 3.1 on 2022-03-09 01:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('Natys Juane', 'Natys Juane'), ('Natys Bakery', 'Natys Bakery'), ('Natys Coffe', 'Natys Coffe')], default='Natys Juane', max_length=170)),
                ('unity', models.CharField(max_length=170)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
